import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useRef, useState } from "react";
import { Search, ShoppingCart, Trash2, Minus, Plus, Banknote, CreditCard, QrCode, History, ScanBarcode, Settings } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { fetchAdminProducts, fetchCategories, type AdminProduct } from "@/lib/catalog";
import { ProductImage } from "@/components/ProductImage";
import { brl } from "@/lib/format";
import { AdminPage } from "@/components/admin/ui";
import { loadPosSettings } from "@/lib/pos-terminal";
export const Route=createFileRoute("/admin/pdv")({component:PosPage});
type CartLine={product:AdminProduct;quantity:number};
function PosPage(){
 const qc=useQueryClient(); const [search,setSearch]=useState(""); const [category,setCategory]=useState(""); const [cart,setCart]=useState<CartLine[]>([]); const [payment,setPayment]=useState("dinheiro"); const [discount,setDiscount]=useState(""); const [received,setReceived]=useState(""); const [busy,setBusy]=useState(false); const [scanStatus,setScanStatus]=useState("Leitor pronto"); const request=useRef(crypto.randomUUID());
 const {data:products}=useQuery({queryKey:["admin","products"],queryFn:fetchAdminProducts}); const {data:categories}=useQuery({queryKey:["categories"],queryFn:fetchCategories});
 const list=((products??[]) as AdminProduct[]).filter(p=>p.is_active&&p.stock>0&&(!category||p.category_id===category)&&(!search||[p.name,p.barcode??""].join(" ").toLowerCase().includes(search.toLowerCase())));
 const subtotal=cart.reduce((s,l)=>s+Number(l.product.promo_price??l.product.price)*l.quantity,0); const disc=Math.min(Math.max(Number(discount)||0,0),subtotal); const total=subtotal-disc; const change=Math.max((Number(received)||0)-total,0);
 const add=(p:AdminProduct)=>setCart(c=>{const hit=c.find(x=>x.product.id===p.id);return hit?c.map(x=>x.product.id===p.id?{...x,quantity:Math.min(x.quantity+1,p.stock)}:x):[...c,{product:p,quantity:1}]}); const qty=(id:string,d:number)=>setCart(c=>c.map(x=>x.product.id===id?{...x,quantity:x.quantity+d}:x).filter(x=>x.quantity>0));
 const finish=async()=>{if(!cart.length)return toast.error("Adicione produtos à venda.");if(payment==="dinheiro"&&received&&Number(received)<total)return toast.error("Valor recebido é menor que o total.");setBusy(true);try{const {data,error}=await supabase.rpc("admin_create_pos_sale" as never,{p_items:cart.map(x=>({product_id:x.product.id,quantity:x.quantity})),p_payment_method:payment,p_discount:disc,p_amount_received:payment==="dinheiro"&&received?Number(received):null,p_client_request_id:request.current} as never);if(error)throw error;const r=data as any;toast.success(`Venda #${r.sale_number} finalizada • ${brl(Number(r.total))}`);setCart([]);setDiscount("");setReceived("");request.current=crypto.randomUUID();void qc.invalidateQueries({queryKey:["admin","products"]});void navigate({to:"/admin/pdv/venda/$id",params:{id:String(r.sale_id)}});}catch(e:any){toast.error(String(e?.message??e).includes("ESTOQUE_INSUFICIENTE")?"Estoque insuficiente. Atualize a venda.":"Não foi possível finalizar a venda.");}finally{setBusy(false)}};
 return <AdminPage><div className="mb-1 flex flex-wrap items-end justify-between gap-2"><div><h1 className="font-display text-xl font-extrabold">PDV</h1><p className="text-xs text-muted-foreground">Venda presencial • estoque integrado ao SAIDERA</p></div><div className="flex gap-2"><Link to="/admin/pdv/vendas" className="flex items-center gap-1 rounded-xl border border-border bg-card px-3 py-2 text-xs font-bold"><History className="h-4 w-4"/>Histórico</Link><Link to="/admin/pdv/configuracoes" className="flex items-center gap-1 rounded-xl border border-border bg-card px-3 py-2 text-xs font-bold"><Settings className="h-4 w-4"/>Terminal</Link></div></div>
 <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_380px]"><section className="min-w-0 space-y-3"><div className="surface-card p-3"><div className="flex items-center gap-2"><Search className="h-5 w-5 text-muted-foreground"/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(terminal.scannerEnabled&&e.key==="Enter"){const code=search.trim();const exact=((products??[]) as AdminProduct[]).find(p=>p.barcode===code);if(exact&&exact.is_active&&exact.stock>0){add(exact);setSearch("");setScanStatus(`Adicionado: ${exact.name}`);toast.success(`${exact.name} adicionado`)}else if(code){setScanStatus("Código não encontrado");toast.error("Código de barras não cadastrado ou produto sem estoque.")}}}} placeholder="Produto ou código de barras..." className="w-full bg-transparent text-sm outline-none"/></div><div className="mt-2 flex items-center gap-1 text-[11px] text-muted-foreground"><ScanBarcode className="h-3.5 w-3.5"/>{terminal.scannerEnabled?scanStatus:"Leitor desativado"} • passe o código e o leitor envia Enter automaticamente</div></div>
 <div className="flex gap-2 overflow-x-auto pb-1"><button onClick={()=>setCategory("")} className={pill(!category)}>Todos</button>{(categories??[]).map(c=><button key={c.id} onClick={()=>setCategory(c.id)} className={pill(category===c.id)}>{c.name}</button>)}</div>
 <div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-4">{list.map(p=><button key={p.id} onClick={()=>add(p)} className="surface-card overflow-hidden text-left transition hover:border-accent"><ProductImage product={p} className="h-28 w-full sm:h-36"/><div className="space-y-1 p-3"><p className="line-clamp-2 text-sm font-bold">{p.name}</p><p className="font-display text-base font-extrabold">{brl(Number(p.promo_price??p.price))}</p><p className="text-[11px] text-muted-foreground">Estoque: {p.stock}</p><span className="mt-1 inline-flex h-8 w-8 items-center justify-center rounded-full bg-accent font-bold text-accent-foreground"><Plus className="h-4 w-4"/></span></div></button>)}</div></section>
 <aside className="surface-card h-fit overflow-hidden xl:sticky xl:top-28"><div className="flex items-center justify-between border-b border-border p-4"><h2 className="flex items-center gap-2 font-display text-lg font-extrabold"><ShoppingCart className="h-5 w-5 text-accent-strong"/>Venda atual</h2><button onClick={()=>setCart([])} className="text-xs font-bold text-destructive">Limpar</button></div>
 <div className="max-h-[42vh] divide-y divide-border overflow-y-auto">{cart.length===0?<p className="p-8 text-center text-sm text-muted-foreground">Carrinho vazio</p>:cart.map(l=><div key={l.product.id} className="flex items-center gap-3 p-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{l.product.name}</p><p className="text-xs text-muted-foreground">{brl(Number(l.product.promo_price??l.product.price))} un.</p></div><div className="flex items-center rounded-lg border border-border"><button onClick={()=>qty(l.product.id,-1)} className="p-2"><Minus className="h-3 w-3"/></button><span className="w-7 text-center text-sm font-bold">{l.quantity}</span><button onClick={()=>qty(l.product.id,1)} className="p-2"><Plus className="h-3 w-3"/></button></div><button onClick={()=>setCart(c=>c.filter(x=>x.product.id!==l.product.id))}><Trash2 className="h-4 w-4 text-destructive"/></button></div>)}</div>
 <div className="space-y-3 border-t border-border p-4"><label className="flex items-center justify-between text-sm"><span>Desconto (R$)</span><input value={discount} onChange={e=>setDiscount(e.target.value)} inputMode="decimal" className="w-24 rounded-lg border border-input px-2 py-1.5 text-right"/></label><div className="flex justify-between text-sm text-muted-foreground"><span>Subtotal</span><span>{brl(subtotal)}</span></div><div className="flex justify-between font-display text-2xl font-extrabold"><span>Total</span><span className="text-accent-strong">{brl(total)}</span></div>
 <div className="grid grid-cols-3 gap-2">{[["dinheiro","Dinheiro",Banknote],["pix","PIX",QrCode],["cartao","Cartão",CreditCard]].map(([id,label,Icon]:any)=><button key={id} onClick={()=>setPayment(id)} className={`rounded-xl border p-2 text-xs font-bold ${payment===id?"border-accent bg-accent/15":"border-border"}`}><Icon className="mx-auto mb-1 h-4 w-4"/>{label}</button>)}</div>{payment==="dinheiro"&&<div className="grid grid-cols-2 gap-2"><label className="text-xs">Valor recebido<input value={received} onChange={e=>setReceived(e.target.value)} inputMode="decimal" className="mt-1 w-full rounded-xl border border-input px-3 py-2 text-sm"/></label><div className="rounded-xl bg-success/10 p-2 text-xs">Troco<p className="text-lg font-extrabold text-success">{brl(change)}</p></div></div>}
 <button disabled={busy||!cart.length} onClick={finish} className="w-full rounded-xl bg-primary py-3 text-sm font-extrabold text-primary-foreground disabled:opacity-50">{busy?"FINALIZANDO...":"FINALIZAR VENDA"}</button></div></aside></div></AdminPage>
}
const pill=(active:boolean)=>`whitespace-nowrap rounded-full px-3 py-2 text-xs font-bold ${active?"bg-accent text-accent-foreground":"bg-secondary text-secondary-foreground"}`;
