import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery,useQueryClient } from "@tanstack/react-query";
import { useEffect } from "react"; import { Clock,MapPin,ChevronRight,Truck,PackageCheck } from "lucide-react"; import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client"; import { brl,timeBR } from "@/lib/format"; import { STATUS_LABEL } from "@/lib/orders"; import { AdminPage,StateBlock } from "@/components/admin/ui";
export const Route=createFileRoute("/admin/delivery")({component:DeliveryOps});
type O={id:string;order_number:number;status:string;total:number;payment_method:string;payment_status:string;created_at:string;customer_name:string|null;address_snapshot:{street?:string;number?:string;neighborhood?:string}|null;order_items?:{id:string;product_name:string;quantity:number}[]};
const cols=[{id:"novo",title:"Recebidos",next:"confirmado",action:"Aceitar pedido"},{id:"confirmado",title:"Confirmados",next:"em_preparo",action:"Iniciar separação"},{id:"em_preparo",title:"Em preparação",next:"pronto",action:"Liberar pedido"},{id:"pronto",title:"Prontos",next:"saiu_para_entrega",action:"Saiu para entrega"},{id:"saiu_para_entrega",title:"Em rota",next:null,action:null}] as const;
function DeliveryOps(){const qc=useQueryClient();const q=useQuery({queryKey:["admin","delivery-ops"],queryFn:async()=>{const {data,error}=await supabase.from("orders").select("*, order_items(id,product_name,quantity)").not("status","in","(entregue,cancelado)").order("created_at",{ascending:true}).limit(200);if(error)throw error;return(data??[]) as O[]},refetchInterval:15000});
useEffect(()=>{const ch=supabase.channel("delivery-ops").on("postgres_changes",{event:"*",schema:"public",table:"orders"},()=>void qc.invalidateQueries({queryKey:["admin","delivery-ops"]})).subscribe();return()=>{void supabase.removeChannel(ch)}},[qc]);
const move=async(o:O,status:string)=>{const {error}=await supabase.rpc("set_order_status",{p_order_id:o.id,p_status:status});if(error)toast.error("Não foi possível atualizar o pedido.");else{toast.success(`Pedido #${o.order_number}: ${STATUS_LABEL[status]}`);void qc.invalidateQueries({queryKey:["admin","delivery-ops"]})}};
return <AdminPage><div className="flex items-end justify-between gap-3"><div><h1 className="font-display text-xl font-extrabold">Central Delivery</h1><p className="text-xs text-muted-foreground">Receba, prepare e libere os pedidos em uma única tela.</p></div><span className="rounded-full bg-success/10 px-3 py-1.5 text-xs font-bold text-success">● Tempo real</span></div><StateBlock loading={q.isLoading} error={q.error} empty={(q.data??[]).length===0} emptyText="Nenhum pedido em andamento."/>
<div className="flex snap-x gap-3 overflow-x-auto pb-3 xl:grid xl:grid-cols-5 xl:overflow-visible">{cols.map(col=>{const items=(q.data??[]).filter(o=>o.status===col.id);return <section key={col.id} className="w-[86vw] max-w-[330px] shrink-0 snap-start rounded-2xl bg-secondary/55 p-2 xl:w-auto xl:max-w-none"><div className="mb-2 flex items-center justify-between px-2 py-1"><h2 className="text-sm font-extrabold">{col.title}</h2><span className="grid h-6 min-w-6 place-items-center rounded-full bg-card px-1 text-xs font-bold">{items.length}</span></div><div className="space-y-2">{items.map(o=><article key={o.id} className="surface-card overflow-hidden"><div className="border-b border-border p-3"><div className="flex justify-between gap-2"><div><p className="font-display text-base font-extrabold">#{o.order_number}</p><p className="text-xs font-semibold">{o.customer_name??"Cliente"}</p></div><div className="text-right"><p className="font-bold">{brl(o.total)}</p><p className="text-[10px] text-muted-foreground">{o.payment_method.toUpperCase()}</p></div></div><p className="mt-2 flex items-center gap-1 text-[11px] text-muted-foreground"><Clock className="h-3 w-3"/>{timeBR(o.created_at)}</p>{o.address_snapshot&&<p className="mt-1 flex items-start gap-1 text-[11px] text-muted-foreground"><MapPin className="mt-0.5 h-3 w-3 shrink-0"/>{o.address_snapshot.street}, {o.address_snapshot.number} — {o.address_snapshot.neighborhood}</p>}</div><ul className="space-y-1 p-3 text-xs">{(o.order_items??[]).map(i=><li key={i.id}><b>{i.quantity}x</b> {i.product_name}</li>)}</ul><div className="flex gap-2 p-3 pt-0">{col.next&&<button onClick={()=>void move(o,col.next!)} className="flex flex-1 items-center justify-center gap-1 rounded-xl bg-primary px-2 py-2.5 text-xs font-bold text-primary-foreground">{col.id==="pronto"?<Truck className="h-4 w-4"/>:<PackageCheck className="h-4 w-4"/>}{col.action}</button>}<Link to="/pedido/$id" params={{id:o.id}} className="grid w-10 place-items-center rounded-xl border border-border bg-card"><ChevronRight className="h-4 w-4"/></Link></div></article>)}</div></section>})}</div></AdminPage>}
