import { createFileRoute,Link } from "@tanstack/react-router";import { useState } from "react";import { ArrowLeft,Monitor,Printer,ScanBarcode,CreditCard,Save } from "lucide-react";import { toast } from "sonner";import { AdminPage } from "@/components/admin/ui";import { DEFAULT_POS_SETTINGS,loadPosSettings,savePosSettings,type PosTerminalSettings } from "@/lib/pos-terminal";
export const Route=createFileRoute("/admin/pdv/configuracoes")({component:Settings});
function Settings(){const [v,setV]=useState<PosTerminalSettings>(()=>loadPosSettings());const set=<K extends keyof PosTerminalSettings>(k:K,x:PosTerminalSettings[K])=>setV(s=>({...s,[k]:x}));const save=()=>{savePosSettings(v);toast.success("Configuração deste terminal salva.")};return <AdminPage><div className="flex items-end justify-between gap-3"><div><h1 className="font-display text-xl font-extrabold">Terminal PDV</h1><p className="text-xs text-muted-foreground">Configuração local deste computador ou tablet.</p></div><Link to="/admin/pdv" className="rounded-xl border border-border bg-card px-3 py-2 text-xs font-bold"><ArrowLeft className="mr-1 inline h-4 w-4"/>PDV</Link></div><div className="grid gap-3 lg:grid-cols-2">
<Card icon={Monitor} title="Identificação"><label className="text-xs font-semibold">Nome do terminal<input value={v.terminalName} onChange={e=>set("terminalName",e.target.value)} className="mt-1 w-full rounded-xl border border-input px-3 py-2 text-sm" placeholder="Caixa 1"/></label><p className="text-[11px] text-muted-foreground">Ajuda a identificar o computador na operação. A configuração fica salva neste dispositivo.</p></Card>
<Card icon={Printer} title="Cupom térmico"><p className="text-xs font-semibold">Largura do papel</p><div className="grid grid-cols-2 gap-2">{(["58","80"] as const).map(x=><button key={x} onClick={()=>set("receiptWidth",x)} className={pick(v.receiptWidth===x)}>{x} mm</button>)}</div><Toggle checked={v.autoPrint} onChange={x=>set("autoPrint",x)} label="Abrir impressão automaticamente após finalizar"/></Card>
<Card icon={ScanBarcode} title="Leitor de código de barras"><Toggle checked={v.scannerEnabled} onChange={x=>set("scannerEnabled",x)} label="Leitor habilitado"/><div className="rounded-xl bg-secondary p-3 text-[11px] text-muted-foreground">Modo configurado: leitor USB/Bluetooth tipo teclado, finalizando a leitura com <b>Enter</b>.</div></Card>
<Card icon={CreditCard} title="Pagamento Stone"><p className="text-xs font-semibold">Integração do terminal</p><button onClick={()=>set("paymentBridge","manual")} className={pick(v.paymentBridge==="manual")}>Manual — disponível agora</button><button disabled className="w-full rounded-xl border border-border bg-secondary/50 p-3 text-left text-xs opacity-70"><b>Stone TEF — preparado para etapa futura</b><br/><span className="text-muted-foreground">Será habilitado quando o componente local/credenciais estiverem configurados neste PC.</span></button></Card>
</div><div className="flex gap-2"><button onClick={()=>setV(DEFAULT_POS_SETTINGS)} className="rounded-xl border border-border bg-card px-4 py-3 text-sm font-bold">Restaurar padrão</button><button onClick={save} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-extrabold text-primary-foreground"><Save className="h-4 w-4"/>SALVAR CONFIGURAÇÃO</button></div></AdminPage>}
function Card({icon:Icon,title,children}:any){return <section className="surface-card space-y-3 p-4"><h2 className="flex items-center gap-2 font-display font-extrabold"><Icon className="h-5 w-5 text-accent-strong"/>{title}</h2>{children}</section>}function Toggle({checked,onChange,label}:any){return <label className="flex cursor-pointer items-center justify-between gap-3 rounded-xl border border-border p-3 text-xs font-semibold"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="h-4 w-4 accent-current"/></label>}const pick=(on:boolean)=>`w-full rounded-xl border p-3 text-left text-xs font-bold ${on?"border-accent bg-accent/15":"border-border bg-card"}`;
