-- PDV presencial integrado ao estoque único do SAIDERA.
CREATE TABLE IF NOT EXISTS public.pos_sales (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sale_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  operator_user_id uuid NOT NULL,
  payment_method text NOT NULL CHECK (payment_method IN ('dinheiro','pix','cartao','outros')),
  subtotal numeric(10,2) NOT NULL CHECK (subtotal >= 0),
  discount numeric(10,2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
  total numeric(10,2) NOT NULL CHECK (total >= 0),
  amount_received numeric(10,2),
  change_amount numeric(10,2),
  status text NOT NULL DEFAULT 'concluida' CHECK (status IN ('concluida','cancelada')),
  client_request_id text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  canceled_at timestamptz,
  canceled_by uuid
);
CREATE TABLE IF NOT EXISTS public.pos_sale_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL REFERENCES public.pos_sales(id) ON DELETE RESTRICT,
  product_id uuid REFERENCES public.products(id) ON DELETE SET NULL,
  product_name text NOT NULL,
  image_url text,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric(10,2) NOT NULL CHECK (unit_price >= 0),
  total_price numeric(10,2) NOT NULL CHECK (total_price >= 0)
);
ALTER TABLE public.pos_sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_sale_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY pos_sales_admin_read ON public.pos_sales FOR SELECT TO authenticated USING (public.is_admin());
CREATE POLICY pos_sale_items_admin_read ON public.pos_sale_items FOR SELECT TO authenticated USING (public.is_admin());
GRANT SELECT ON public.pos_sales, public.pos_sale_items TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_create_pos_sale(p_items jsonb,p_payment_method text,p_discount numeric DEFAULT 0,p_amount_received numeric DEFAULT NULL,p_client_request_id text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='public' AS $$
DECLARE v_user uuid:=auth.uid(); v_item jsonb; v_pid uuid; v_qty int; v_prod public.products%ROWTYPE; v_unit numeric(10,2); v_sub numeric(10,2):=0; v_discount numeric(10,2):=greatest(coalesce(p_discount,0),0); v_total numeric(10,2); v_sale public.pos_sales%ROWTYPE; v_before int; v_after int; v_item_id uuid;
BEGIN
 IF NOT public.is_admin() THEN RAISE EXCEPTION 'SEM_PERMISSAO'; END IF;
 IF p_items IS NULL OR jsonb_typeof(p_items)<>'array' OR jsonb_array_length(p_items)=0 THEN RAISE EXCEPTION 'CARRINHO_VAZIO'; END IF;
 IF p_payment_method NOT IN ('dinheiro','pix','cartao','outros') THEN RAISE EXCEPTION 'PAGAMENTO_INVALIDO'; END IF;
 IF nullif(btrim(coalesce(p_client_request_id,'')),'') IS NULL THEN RAISE EXCEPTION 'CHAVE_OBRIGATORIA'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended('pos:'||p_client_request_id,0));
 SELECT * INTO v_sale FROM public.pos_sales WHERE client_request_id=p_client_request_id;
 IF v_sale.id IS NOT NULL THEN RETURN jsonb_build_object('sale_id',v_sale.id,'sale_number',v_sale.sale_number,'total',v_sale.total,'change',v_sale.change_amount); END IF;
 FOR v_item IN SELECT * FROM jsonb_array_elements(p_items) LOOP
   v_pid:=(v_item->>'product_id')::uuid; v_qty:=coalesce((v_item->>'quantity')::int,0);
   IF v_qty<=0 THEN RAISE EXCEPTION 'QUANTIDADE_INVALIDA'; END IF;
   SELECT * INTO v_prod FROM public.products WHERE id=v_pid AND is_active=true FOR UPDATE;
   IF v_prod.id IS NULL THEN RAISE EXCEPTION 'PRODUTO_INDISPONIVEL'; END IF;
   IF v_prod.stock<v_qty THEN RAISE EXCEPTION 'ESTOQUE_INSUFICIENTE:%',v_prod.name; END IF;
   v_unit:=coalesce(v_prod.promo_price,v_prod.price); v_sub:=v_sub+(v_unit*v_qty);
 END LOOP;
 v_discount:=least(v_discount,v_sub); v_total:=v_sub-v_discount;
 IF p_payment_method='dinheiro' AND p_amount_received IS NOT NULL AND p_amount_received<v_total THEN RAISE EXCEPTION 'VALOR_RECEBIDO_INSUFICIENTE'; END IF;
 INSERT INTO public.pos_sales(operator_user_id,payment_method,subtotal,discount,total,amount_received,change_amount,client_request_id)
 VALUES(v_user,p_payment_method,v_sub,v_discount,v_total,p_amount_received,CASE WHEN p_payment_method='dinheiro' AND p_amount_received IS NOT NULL THEN p_amount_received-v_total ELSE 0 END,p_client_request_id) RETURNING * INTO v_sale;
 FOR v_item IN SELECT * FROM jsonb_array_elements(p_items) LOOP
   v_pid:=(v_item->>'product_id')::uuid; v_qty:=(v_item->>'quantity')::int;
   SELECT * INTO v_prod FROM public.products WHERE id=v_pid FOR UPDATE; v_unit:=coalesce(v_prod.promo_price,v_prod.price); v_before:=v_prod.stock;
   UPDATE public.products SET stock=stock-v_qty WHERE id=v_pid RETURNING stock INTO v_after;
   INSERT INTO public.pos_sale_items(sale_id,product_id,product_name,image_url,quantity,unit_price,total_price) VALUES(v_sale.id,v_prod.id,v_prod.name,v_prod.image_url,v_qty,v_unit,v_unit*v_qty) RETURNING id INTO v_item_id;
   PERFORM public.record_stock_movement(v_prod.id,'venda',-v_qty,v_before,v_after,'PDV #'||v_sale.sale_number,NULL,v_user,'rpc','pdv:'||v_item_id::text);
 END LOOP;
 RETURN jsonb_build_object('sale_id',v_sale.id,'sale_number',v_sale.sale_number,'subtotal',v_sub,'discount',v_discount,'total',v_total,'change',coalesce(v_sale.change_amount,0));
END $$;
REVOKE ALL ON FUNCTION public.admin_create_pos_sale(jsonb,text,numeric,numeric,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.admin_create_pos_sale(jsonb,text,numeric,numeric,text) TO authenticated;
