/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as EnderecosRouteImport } from './routes/enderecos'
import { Route as EntregadorRouteImport } from './routes/entregador'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminEntregaRouteImport } from './routes/admin.entrega'
import { Route as AdminEntregadoresRouteImport } from './routes/admin.entregadores'
import { Route as AdminEstoqueRouteImport } from './routes/admin.estoque'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminPromocoesRouteImport } from './routes/admin.promocoes'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EnderecosRoute = EnderecosRouteImport.update({
  id: '/enderecos',
  path: '/enderecos',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregadorRoute = EntregadorRouteImport.update({
  id: '/entregador',
  path: '/entregador',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntregaRoute = AdminEntregaRouteImport.update({
  id: '/entrega',
  path: '/entrega',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntregadoresRoute = AdminEntregadoresRouteImport.update({
  id: '/entregadores',
  path: '/entregadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstoqueRoute = AdminEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromocoesRoute = AdminPromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => AdminRoute,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/enderecos': typeof EnderecosRoute
  '/entregador': typeof EntregadorRoute
  '/favoritos': typeof FavoritosRoute
  '/pedidos': typeof PedidosRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/entrega': typeof AdminEntregaRoute
  '/admin/entregadores': typeof AdminEntregadoresRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/enderecos': typeof EnderecosRoute
  '/entregador': typeof EntregadorRoute
  '/favoritos': typeof FavoritosRoute
  '/pedidos': typeof PedidosRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/entrega': typeof AdminEntregaRoute
  '/admin/entregadores': typeof AdminEntregadoresRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/enderecos': typeof EnderecosRoute
  '/entregador': typeof EntregadorRoute
  '/favoritos': typeof FavoritosRoute
  '/pedidos': typeof PedidosRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/entrega': typeof AdminEntregaRoute
  '/admin/entregadores': typeof AdminEntregadoresRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/carrinho'
    | '/categorias'
    | '/checkout'
    | '/conta'
    | '/enderecos'
    | '/entregador'
    | '/favoritos'
    | '/pedidos'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/entrega'
    | '/admin/entregadores'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/promocoes'
    | '/categoria/$slug'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/categorias'
    | '/checkout'
    | '/conta'
    | '/enderecos'
    | '/entregador'
    | '/favoritos'
    | '/pedidos'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/entrega'
    | '/admin/entregadores'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/promocoes'
    | '/categoria/$slug'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/carrinho'
    | '/categorias'
    | '/checkout'
    | '/conta'
    | '/enderecos'
    | '/entregador'
    | '/favoritos'
    | '/pedidos'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/entrega'
    | '/admin/entregadores'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/promocoes'
    | '/categoria/$slug'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CategoriasRoute: typeof CategoriasRoute
  CheckoutRoute: typeof CheckoutRoute
  ContaRoute: typeof ContaRoute
  EnderecosRoute: typeof EnderecosRoute
  EntregadorRoute: typeof EntregadorRoute
  FavoritosRoute: typeof FavoritosRoute
  PedidosRoute: typeof PedidosRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enderecos': {
      id: '/enderecos'
      path: '/enderecos'
      fullPath: '/enderecos'
      preLoaderRoute: typeof EnderecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregador': {
      id: '/entregador'
      path: '/entregador'
      fullPath: '/entregador'
      preLoaderRoute: typeof EntregadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entrega': {
      id: '/admin/entrega'
      path: '/entrega'
      fullPath: '/admin/entrega'
      preLoaderRoute: typeof AdminEntregaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entregadores': {
      id: '/admin/entregadores'
      path: '/entregadores'
      fullPath: '/admin/entregadores'
      preLoaderRoute: typeof AdminEntregadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estoque': {
      id: '/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AdminEstoqueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promocoes': {
      id: '/admin/promocoes'
      path: '/promocoes'
      fullPath: '/admin/promocoes'
      preLoaderRoute: typeof AdminPromocoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminEntregaRoute: typeof AdminEntregaRoute
  AdminEntregadoresRoute: typeof AdminEntregadoresRoute
  AdminEstoqueRoute: typeof AdminEstoqueRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminPromocoesRoute: typeof AdminPromocoesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminEntregaRoute: AdminEntregaRoute,
  AdminEntregadoresRoute: AdminEntregadoresRoute,
  AdminEstoqueRoute: AdminEstoqueRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminPromocoesRoute: AdminPromocoesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CarrinhoRoute: CarrinhoRoute,
  CategoriasRoute: CategoriasRoute,
  CheckoutRoute: CheckoutRoute,
  ContaRoute: ContaRoute,
  EnderecosRoute: EnderecosRoute,
  EntregadorRoute: EntregadorRoute,
  FavoritosRoute: FavoritosRoute,
  PedidosRoute: PedidosRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  PedidoIdRoute: PedidoIdRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
